---
- hosts: all
  become: yes

  vars:
    frontend_image: "hiruniwijendrasinhe/alertfy_frontend:{{ build_number }}"
    backend_image: "hiruniwijendrasinhe/alertfy_backend:{{ build_number }}"
    docker_network_name: mynetwork

  tasks:

    - name: Ensure Docker is installed
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker SDK for Python (required for community.docker)
      ansible.builtin.yum:
        name: python3-docker
        state: present

    # Pull frontend image
    - name: Pull frontend Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: pull

    # Pull backend image
    - name: Pull backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    # Create Docker network
    - name: Create user-defined Docker network
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        state: present

    # Remove old frontend container
    - name: Remove old frontend container if exists
      community.docker.docker_container:
        name: frontendnew
        state: absent
        force_kill: yes

    # Remove old backend container
    - name: Remove old backend container if exists
      community.docker.docker_container:
        name: backendnew
        state: absent
        force_kill: yes

    # Run backend container
    - name: Run backend container
      community.docker.docker_container:
        name: backendnew
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        recreate: yes
        ports:
          - "82:5000"
        networks:
          - name: "{{ docker_network_name }}"
        env_file: /home/ec2-user/backend/.env

    # Run frontend container
    - name: Run frontend container
      community.docker.docker_container:
        name: frontendnew
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        recreate: yes
        ports:
          - "81:80"
        networks:
          - name: "{{ docker_network_name }}"