- hosts: all
  become: yes
  gather_facts: no   # Disable gathering facts to speed up
  vars:
    frontend_image: "hiruniwijendrasinhe/alertfy_frontend:{{ build_number }}"
    backend_image: "hiruniwijendrasinhe/alertfy_backend:{{ build_number }}"
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull frontend Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: pull

    - name: Pull backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Run frontend container
      community.docker.docker_container:
        name: frontendnew
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        ports:
          - "81:3000"
        recreate: yes   # Automatically replaces old container if exists

    - name: Run backend container
      community.docker.docker_container:
        name: backendnew
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "82:5000"
        recreate: yes
